language: go
go:
  - 1.20

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
  - go mod download
  - go get -d .
script:
  - go install .
  - goveralls -service=travis-ci
